CREATE DATABASE IF NOT EXISTS pokedex;

USE pokedex;

CREATE TABLE IF NOT EXISTS pokemones (
id INT AUTO_INCREMENT PRIMARY KEY,
numero_identificador INT NOT NULL UNIQUE,
imagen VARCHAR(255) NOT NULL,
nombre VARCHAR(50) NOT NULL,
tipo VARCHAR(100) NOT NULL,
descripcion TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS administradores (
id INT AUTO_INCREMENT PRIMARY KEY,
user VARCHAR(50) NOT NULL UNIQUE,
pass VARCHAR(30) NOT NULL
);

INSERT INTO administradores(user, pass) VALUES
      ('PabloR','1357'),
      ('PabloE','9876'),
      ('Regina','2468'),
      ('Micaela','1234');

INSERT INTO pokemones (numero_identificador, imagen, nombre, tipo, descripcion) VALUES
      (1, 'img/pokemones/1.png', 'Bulbasaur', 'Planta', 'Bulbasaur es un Pokémon de tipo planta/veneno introducido en la primera generación. Es conocido por tener una semilla de planta en su lomo desde el momento en que nace.'),
      (2, 'img/pokemones/2.png', 'Ivysaur', 'Planta', 'Ivysaur es la evolución de Bulbasaur. Continúa creciendo de forma similar, pero ahora tiene un bulbo más grande en su espalda.'),
      (3, 'img/pokemones/3.png', 'Venusaur', 'Planta', 'Venusaur es la evolución final de Bulbasaur. Es un Pokémon grande y poderoso con una flor en su espalda que libera un aroma dulce y agradable.'),
      (4, 'img/pokemones/4.png', 'Charmander', 'Fuego', 'Charmander es un Pokémon de tipo fuego introducido en la primera generación. Tiene una llama en la punta de su cola que indica su estado de salud y ánimo.'),
      (5, 'img/pokemones/5.png', 'Charmeleon', 'Fuego', 'Charmeleon es la evolución de Charmander. Es un Pokémon más grande y feroz con una llama más grande en la punta de su cola.'),
      (6, 'img/pokemones/6.png', 'Charizard', 'Fuego', 'Charizard es la evolución final de Charmander. Es un Pokémon imponente que puede volar y lanzar poderosas llamaradas de fuego desde su boca.'),
      (7, 'img/pokemones/7.png', 'Squirtle', 'Agua', 'Squirtle es un Pokémon de tipo agua introducido en la primera generación. Tiene una concha en la espalda que le proporciona protección y puede lanzar chorros de agua con gran precisión.'),
      (8, 'img/pokemones/8.png', 'Wartortle', 'Agua', 'Wartortle es la evolución de Squirtle. Es un Pokémon más grande con una cola larga y peluda que usa para nadar rápidamente por el agua.'),
      (9, 'img/pokemones/9.png', 'Blastoise', 'Agua', 'Blastoise es la evolución final de Squirtle. Es un Pokémon extremadamente poderoso con unos cañones de agua en la espalda que puede usar para lanzar potentes chorros de agua.'),
      (10, 'img/pokemones/10.png', 'Caterpie', 'Bicho', 'Caterpie es un Pokémon de tipo bicho introducido en la primera generación. Tiene un cuerpo pequeño y blando que puede enrollar en una bola para protegerse de los depredadores.'),
      (11, 'img/pokemones/11.png', 'Metapod', 'Bicho', 'Metapod es la evolución de Caterpie. Es más grande y resistente que su pre-evolución, y puede endurecer su caparazón para protegerse de los ataques enemigos.'),
      (12, 'img/pokemones/12.png', 'Butterfree', 'Bicho', 'Butterfree es la evolución final de Caterpie. Es un Pokémon extremadamente ágil con unas alas llenas de polvo brillante que puede esparcir para adormecer a sus enemigos.'),
      (13, 'img/pokemones/13.png', 'Weedle', 'Bicho', 'Weedle es un Pokémon de tipo bicho/veneno introducido en la primera generación. Tiene un aguijón venenoso en la parte superior de la cabeza que puede usar para defenderse de los depredadores.'),
      (14, 'img/pokemones/14.png', 'Kakuna', 'Bicho', 'Kakuna es la evolución de Weedle. Es más grande y resistente que su pre-evolución, y puede endurecer su caparazón para protegerse mientras evoluciona.'),
      (15, 'img/pokemones/15.png', 'Beedrill', 'Bicho', 'Beedrill es la evolución final de Weedle. Es un Pokémon extremadamente agresivo con aguijones venenosos en los brazos que puede usar para atacar a sus enemigos.'),
      (16, 'img/pokemones/16.png', 'Pidgey', 'Normal', 'Pidgey es un Pokémon de tipo normal/volador introducido en la primera generación. Tiene una vista aguda y puede volar a grandes alturas para buscar presas.'),
      (17, 'img/pokemones/17.png', 'Pidgeotto', 'Normal', 'Pidgeotto es la evolución de Pidgey. Es más grande y poderoso que su pre-evolución, y puede volar a grandes velocidades para atrapar a sus presas.'),
      (18, 'img/pokemones/18.png', 'Pidgeot', 'Normal', 'Pidgeot es la evolución final de Pidgey. Es un Pokémon extremadamente rápido y ágil con unas alas enormes que puede usar para crear ráfagas de viento.'),
      (19, 'img/pokemones/19.png', 'Rattata', 'Normal', 'Rattata es un Pokémon de tipo normal introducido en la primera generación. Es conocido por su agilidad y su capacidad para morder a sus enemigos con sus dientes afilados.'),
      (20, 'img/pokemones/20.png', 'Raticate', 'Normal', 'Raticate es la evolución de Rattata. Es más grande y poderoso que su pre-evolución, y puede morder con fuerza suficiente para romper huesos.'),
      (21, 'img/pokemones/21.png', 'Spearow', 'Normal', 'Spearow es un Pokémon de tipo normal/volador introducido en la primera generación. Es conocido por su ferocidad en la batalla y su capacidad para volar a grandes alturas.'),
      (22, 'img/pokemones/22.png', 'Fearow', 'Normal', 'Fearow es la evolución de Spearow. Es más grande y poderoso que su pre-evolución, y puede lanzar ataques devastadores desde el aire con su pico afilado.'),
      (23, 'img/pokemones/23.png', 'Ekans', 'Veneno', 'Ekans es un Pokémon de tipo veneno introducido en la primera generación. Tiene una mandíbula flexible que puede abrir hasta 180 grados y puede lanzar ataques venenosos.'),
      (24, 'img/pokemones/24.png', 'Arbok', 'Veneno', 'Arbok es la evolución de Ekans. Es más grande y poderoso que su pre-evolución, y puede lanzar ataques venenosos desde sus colmillos afilados.'),
      (25, 'img/pokemones/25.png', 'Pikachu', 'Eléctrico', 'Pikachu es un Pokémon de tipo eléctrico introducido en la primera generación. Es conocido por su carisma y su capacidad para lanzar potentes ataques eléctricos.'),
      (26, 'img/pokemones/26.png', 'Raichu', 'Eléctrico', 'Raichu es la evolución de Pikachu. Es más grande y poderoso que su pre-evolución, y puede generar grandes cantidades de electricidad en su cuerpo.'),
      (27, 'img/pokemones/27.png', 'Sandshrew', 'Tierra', 'Sandshrew es un Pokémon de tipo tierra introducido en la primera generación. Tiene una piel dura y resistente que puede usar para protegerse de los ataques enemigos.'),
      (28, 'img/pokemones/28.png', 'Sandslash', 'Tierra', 'Sandslash es la evolución de Sandshrew. Es más grande y poderoso que su pre-evolución, y puede lanzar ataques rápidos y precisos con sus garras afiladas.'),
      (29, 'img/pokemones/29.png', 'Nidoran♀', 'Veneno', 'Nidoran♀ es un Pokémon de tipo veneno introducido en la primera generación. Tiene una cola venenosa que puede usar para defenderse de los depredadores.'),
      (30, 'img/pokemones/30.png', 'Nidorina', 'Veneno', 'Nidorina es la evolución de Nidoran♀. Es más grande y poderosa que su pre-evolución, y puede lanzar ataques venenosos desde sus colmillos afilados.'),
      (31, 'img/pokemones/31.png', 'Nidoqueen', 'Veneno', 'Nidoqueen es la evolución final de Nidoran♀. Es un Pokémon extremadamente poderoso con una armadura dura y resistente que puede usar para defenderse de los ataques enemigos.'),
      (32, 'img/pokemones/32.png', 'Nidoran♂', 'Veneno', 'Nidoran♂ es un Pokémon de tipo veneno introducido en la primera generación. Tiene una cola venenosa que puede usar para defenderse de los depredadores.'),
      (33, 'img/pokemones/33.png', 'Nidorino', 'Veneno', 'Nidorino es la evolución de Nidoran♂. Es más grande y poderoso que su pre-evolución, y puede lanzar ataques venenosos desde sus colmillos afilados.'),
      (34, 'img/pokemones/34.png', 'Nidoking', 'Veneno', 'Nidoking es la evolución final de Nidoran♂. Es un Pokémon extremadamente poderoso con una armadura dura y resistente que puede usar para defenderse de los ataques enemigos.'),
      (35, 'img/pokemones/35.png', 'Clefairy', 'Hada', 'Clefairy es un Pokémon de tipo hada introducido en la primera generación. Es conocido por su ternura y su capacidad para lanzar ataques mágicos.'),
      (36, 'img/pokemones/36.png', 'Clefable', 'Hada', 'Clefable es la evolución de Clefairy. Es más grande y poderoso que su pre-evolución, y puede lanzar poderosos ataques mágicos desde su varita.'),
      (37, 'img/pokemones/37.png', 'Vulpix', 'Fuego', 'Vulpix es un Pokémon de tipo fuego introducido en la primera generación. Tiene una cola en llamas que puede usar para crear ilusiones y protegerse de los depredadores.'),
      (38, 'img/pokemones/38.png', 'Ninetales', 'Fuego', 'Ninetales es la evolución de Vulpix. Es más grande y poderoso que su pre-evolución, y puede lanzar bolas de fuego desde su boca para atacar a sus enemigos.'),
      (39, 'img/pokemones/39.png', 'Jigglypuff', 'Normal', 'Jigglypuff es un Pokémon de tipo normal/hada introducido en la primera generación. Es conocido por su canto hipnótico y su capacidad para hacer dormir a sus enemigos.'),
      (40, 'img/pokemones/40.png', 'Wigglytuff', 'Normal', 'Wigglytuff es la evolución de Jigglypuff. Es más grande y poderoso que su pre-evolución, y puede lanzar ondas de sonido devastadoras desde su boca.'),
      (41, 'img/pokemones/41.png', 'Zubat', 'Veneno', 'Zubat es un Pokémon de tipo veneno/volador introducido en la primera generación. Es conocido por su habilidad para volar en completa oscuridad y sorprender a sus presas.'),
      (42, 'img/pokemones/42.png', 'Golbat', 'Veneno', 'Golbat es la evolución de Zubat. Es más grande y poderoso que su pre-evolución, y puede lanzar potentes ultrasonidos para desorientar a sus enemigos.'),
      (43, 'img/pokemones/43.png', 'Oddish', 'Planta', 'Oddish es un Pokémon de tipo planta/veneno introducido en la primera generación. Tiene un cuerpo pequeño y redondo que puede usar para camuflarse en la maleza.'),
      (44, 'img/pokemones/44.png', 'Gloom', 'Planta', 'Gloom es la evolución de Oddish. Es más grande y poderoso que su pre-evolución, y puede lanzar un olor fétido desde su flor para repeler a sus enemigos.'),
      (45, 'img/pokemones/45.png', 'Vileplume', 'Planta', 'Vileplume es la evolución final de Oddish. Es un Pokémon extremadamente poderoso con una flor gigante en la cabeza que puede lanzar polen venenoso para atacar a sus enemigos.'),
      (46, 'img/pokemones/46.png', 'Paras', 'Bicho', 'Paras es un Pokémon de tipo bicho/planta introducido en la primera generación. Tiene hongos en la espalda que puede usar para camuflarse en el bosque y atacar a sus presas.'),
      (47, 'img/pokemones/47.png', 'Parasect', 'Bicho', 'Parasect es la evolución de Paras. Es más grande y poderoso que su pre-evolución, y puede lanzar esporas venenosas desde los hongos en su espalda para debilitar a sus enemigos.'),
      (48, 'img/pokemones/48.png', 'Venonat', 'Bicho', 'Venonat es un Pokémon de tipo bicho/veneno introducido en la primera generación. Tiene unos ojos grandes y compuestos que puede usar para ver en la oscuridad y detectar el peligro.'),
      (49, 'img/pokemones/49.png', 'Venomoth', 'Bicho', 'Venomoth es la evolución de Venonat. Es más grande y poderoso que su pre-evolución, y puede lanzar potentes ataques de veneno desde su trompa larga y delgada.'),
      (50, 'img/pokemones/50.png', 'Diglett', 'Tierra', 'Diglett es un Pokémon de tipo tierra introducido en la primera generación. Tiene una cabeza pequeña y redonda que puede usar para excavar túneles en la tierra a gran velocidad.'),
      (51, 'img/pokemones/51.png', 'Dugtrio', 'Tierra', 'Dugtrio es la evolución de Diglett. Es más grande y poderoso que su pre-evolución, y puede excavar túneles aún más rápido con la ayuda de sus dos compañeros.'),
      (52, 'img/pokemones/52.png', 'Meowth', 'Normal', 'Meowth es un Pokémon de tipo normal introducido en la primera generación. Es conocido por su habilidad para rastrear objetos de valor y su amor por las monedas.'),
      (53, 'img/pokemones/53.png', 'Persian', 'Normal', 'Persian es la evolución de Meowth. Es más grande y poderoso que su pre-evolución, y puede lanzar ataques rápidos y precisos con sus garras afiladas.'),
      (54, 'img/pokemones/54.png', 'Psyduck', 'Agua', 'Psyduck es un Pokémon de tipo agua introducido en la primera generación. Tiene un dolor de cabeza constante que puede causar que use ataques psíquicos sin control.'),
      (55, 'img/pokemones/55.png', 'Golduck', 'Agua', 'Golduck es la evolución de Psyduck. Es más grande y poderoso que su pre-evolución, y puede nadar a grandes velocidades gracias a su cuerpo aerodinámico.'),
      (56, 'img/pokemones/56.png', 'Mankey', 'Lucha', 'Mankey es un Pokémon de tipo lucha introducido en la primera generación. Es conocido por su temperamento violento y su capacidad para lanzar potentes ataques con sus puños.'),
      (57, 'img/pokemones/57.png', 'Primeape', 'Lucha', 'Primeape es la evolución de Mankey. Es más grande y poderoso que su pre-evolución, y puede volverse extremadamente agresivo en la batalla.'),
      (58, 'img/pokemones/58.png', 'Growlithe', 'Fuego', 'Growlithe es un Pokémon de tipo fuego introducido en la primera generación. Es conocido por su lealtad y su capacidad para lanzar potentes llamaradas desde su boca.'),
      (59, 'img/pokemones/59.png', 'Arcanine', 'Fuego', 'Arcanine es la evolución de Growlithe. Es más grande y poderoso que su pre-evolución, y puede correr a velocidades increíbles gracias a sus poderosas patas.'),
      (60, 'img/pokemones/60.png', 'Poliwag', 'Agua', 'Poliwag es un Pokémon de tipo agua introducido en la primera generación. Tiene un cuerpo pequeño y redondeado que puede usar para moverse rápidamente en el agua.'),
      (61, 'img/pokemones/61.png', 'Poliwhirl', 'Agua', 'Poliwhirl es la evolución de Poliwag. Es más grande y poderoso que su pre-evolución, y puede nadar a gran velocidad gracias a sus fuertes aletas.'),
      (62, 'img/pokemones/62.png', 'Poliwrath', 'Agua', 'Poliwrath es la evolución final de Poliwhirl. Es un Pokémon extremadamente fuerte con la habilidad de lanzar potentes golpes de puño.'),
      (63, 'img/pokemones/63.png', 'Abra', 'Psíquico', 'Abra es un Pokémon de tipo psíquico introducido en la primera generación. Tiene la habilidad de leer la mente de los demás y predecir el futuro.'),
      (64, 'img/pokemones/64.png', 'Kadabra', 'Psíquico', 'Kadabra es la evolución de Abra. Es más grande y poderoso que su pre-evolución, y puede lanzar poderosos ataques psíquicos para derrotar a sus enemigos.'),
      (65, 'img/pokemones/65.png', 'Alakazam', 'Psíquico', 'Alakazam es la evolución final de Kadabra. Es un Pokémon extremadamente inteligente con un coeficiente intelectual superior al de la mayoría de los humanos.'),
      (66, 'img/pokemones/66.png', 'Machop', 'Lucha', 'Machop es un Pokémon de tipo lucha introducido en la primera generación. Tiene una fuerza increíble y puede levantar objetos pesados con facilidad.'),
      (67, 'img/pokemones/67.png', 'Machoke', 'Lucha', 'Machoke es la evolución de Machop. Es más grande y poderoso que su pre-evolución, y puede lanzar potentes golpes de puño para derrotar a sus enemigos.'),
      (68, 'img/pokemones/68.png', 'Machamp', 'Lucha', 'Machamp es la evolución final de Machoke. Es un Pokémon extremadamente fuerte con la habilidad de levantar montañas y derrotar a sus enemigos de un solo golpe.'),
      (69, 'img/pokemones/69.png', 'Bellsprout', 'Planta', 'Bellsprout es un Pokémon de tipo planta introducido en la primera generación. Tiene una boca grande y carnívora que puede usar para atrapar a sus presas y defenderse de los depredadores.'),
      (70, 'img/pokemones/70.png', 'Weepinbell', 'Planta', 'Weepinbell es la evolución de Bellsprout. Es más grande y poderoso que su pre-evolución, y puede digerir a sus presas enteras con su estómago ácido.'),
      (71, 'img/pokemones/71.png', 'Victreebel', 'Planta', 'Victreebel es la evolución final de Bellsprout. Es un Pokémon grande y carnívoro con una boca llena de dientes afilados que puede usar para atrapar a sus presas.'),
      (72, 'img/pokemones/72.png', 'Tentacool', 'Agua', 'Tentacool es un Pokémon de tipo agua introducido en la primera generación. Tiene largos tentáculos que puede usar para atrapar a sus presas y defenderse de los depredadores.'),
      (73, 'img/pokemones/73.png', 'Tentacruel', 'Agua', 'Tentacruel es la evolución de Tentacool. Es más grande y poderoso que su pre-evolución, y puede lanzar aguijones venenosos desde los extremos de sus tentáculos.'),
      (74, 'img/pokemones/74.png', 'Geodude', 'Roca', 'Geodude es un Pokémon de tipo roca introducido en la primera generación. Tiene un cuerpo duro y resistente que puede usar para defenderse de los ataques enemigos.'),
      (75, 'img/pokemones/75.png', 'Graveler', 'Roca', 'Graveler es la evolución de Geodude. Es más grande y poderoso que su pre-evolución, y puede rodar por terrenos rocosos a gran velocidad para atacar a sus enemigos.'),
      (76, 'img/pokemones/76.png', 'Golem', 'Roca', 'Golem es la evolución final de Geodude. Es un Pokémon extremadamente fuerte que puede lanzar rocas gigantes para aplastar a sus enemigos.'),
      (77, 'img/pokemones/77.png', 'Ponyta', 'Fuego', 'Ponyta es un Pokémon de tipo fuego introducido en la primera generación. Es conocido por su velocidad y agilidad, y por su crin en llamas que puede usar para atacar a sus enemigos.'),
      (78, 'img/pokemones/78.png', 'Rapidash', 'Fuego', 'Rapidash es la evolución de Ponyta. Es más grande y poderoso que su pre-evolución, y puede correr a velocidades supersónicas con su crin en llamas.'),
      (79, 'img/pokemones/79.png', 'Slowpoke', 'Agua', 'Slowpoke es un Pokémon de tipo agua introducido en la primera generación. Es conocido por ser extremadamente lento y por su capacidad para regenerar partes de su cuerpo.'),
      (80, 'img/pokemones/80.png', 'Slowbro', 'Agua', 'Slowbro es la evolución de Slowpoke. Es más grande y poderoso que su pre-evolución, y puede usar su cola como un ancla para mantenerse en su lugar.'),
      (81, 'img/pokemones/81.png', 'Magnemite', 'Eléctrico', 'Magnemite es un Pokémon de tipo eléctrico introducido en la primera generación. Tiene la habilidad de generar potentes campos magnéticos y de flotar en el aire.'),
      (82, 'img/pokemones/82.png', 'Magneton', 'Eléctrico', 'Magneton es la evolución de Magnemite. Es más grande y poderoso que su pre-evolución, y puede lanzar potentes descargas eléctricas desde sus imanes.'),
      (83, 'img/pokemones/83.png', 'Farfetch’d', 'Normal', 'Farfetch’d es un Pokémon de tipo normal introducido en la primera generación. Es conocido por llevar un puerro en la boca y por su habilidad para usarlo como arma.'),
      (84, 'img/pokemones/84.png', 'Doduo', 'Normal', 'Doduo es un Pokémon de tipo normal introducido en la primera generación. Tiene dos cabezas que pueden trabajar juntas para detectar peligros y atacar a los enemigos.'),
      (85, 'img/pokemones/85.png', 'Dodrio', 'Normal', 'Dodrio es la evolución de Doduo. Es más grande y poderoso que su pre-evolución, y puede correr a gran velocidad y atacar a sus enemigos con sus tres cabezas.'),
      (86, 'img/pokemones/86.png', 'Seel', 'Agua', 'Seel es un Pokémon de tipo agua introducido en la primera generación. Tiene un pelaje grueso que lo protege del frío y le permite nadar a gran velocidad en el agua.'),
      (87, 'img/pokemones/87.png', 'Dewgong', 'Agua', 'Dewgong es la evolución de Seel. Es más grande y poderoso que su pre-evolución, y puede nadar a gran velocidad y romper el hielo con sus colmillos afilados.'),
      (88, 'img/pokemones/88.png', 'Grimer', 'Veneno', 'Grimer es un Pokémon de tipo veneno introducido en la primera generación. Tiene un cuerpo gelatinoso que despide un olor nauseabundo y puede derretir objetos con su ácido.'),
      (89, 'img/pokemones/89.png', 'Muk', 'Veneno', 'Muk es la evolución de Grimer. Es más grande y poderoso que su pre-evolución, y puede lanzar poderosos ataques de lodo y ácido para derrotar a sus enemigos.'),
      (90, 'img/pokemones/90.png', 'Shellder', 'Agua', 'Shellder es un Pokémon de tipo agua introducido en la primera generación. Tiene una concha dura y resistente que puede cerrar para protegerse de los ataques enemigos.'),
      (91, 'img/pokemones/91.png', 'Cloyster', 'Agua', 'Cloyster es la evolución de Shellder. Es más grande y poderoso que su pre-evolución, y puede lanzar potentes chorros de agua y hielo para atacar a sus enemigos.'),
      (92, 'img/pokemones/92.png', 'Gastly', 'Fantasma', 'Gastly es un Pokémon de tipo fantasma introducido en la primera generación. Tiene la habilidad de pasar a través de objetos sólidos y de lanzar ataques de pesadilla.'),
      (93, 'img/pokemones/93.png', 'Haunter', 'Fantasma', 'Haunter es la evolución de Gastly. Es más grande y poderoso que su pre-evolución, y puede hipnotizar a sus enemigos y absorber su energía vital.'),
      (94, 'img/pokemones/94.png', 'Gengar', 'Fantasma', 'Gengar es la evolución final de Haunter. Es un Pokémon extremadamente malvado que disfruta asustando a la gente y causando problemas.'),
      (95, 'img/pokemones/95.png', 'Onix', 'Roca', 'Onix es un Pokémon de tipo roca introducido en la primera generación. Es conocido por ser extremadamente grande y poderoso, y por su capacidad para excavar túneles.'),
      (96, 'img/pokemones/96.png', 'Drowzee', 'Psíquico', 'Drowzee es un Pokémon de tipo psíquico introducido en la primera generación. Tiene la habilidad de hipnotizar a sus enemigos y controlar sus sueños.'),
      (97, 'img/pokemones/97.png', 'Hypno', 'Psíquico', 'Hypno es la evolución de Drowzee. Es más grande y poderoso que su pre-evolución, y puede controlar los sueños de las personas y hacer que hagan cosas que no quieren.'),
      (98, 'img/pokemones/98.png', 'Krabby', 'Agua', 'Krabby es un Pokémon de tipo agua introducido en la primera generación. Tiene una pinza fuerte y afilada que puede usar para atrapar a sus presas y defenderse de los depredadores.'),
      (99, 'img/pokemones/99.png', 'Kingler', 'Agua', 'Kingler es la evolución de Krabby. Es más grande y poderoso que su pre-evolución, y puede aplastar con su pinza a cualquier cosa que se interponga en su camino.'),
      (100, 'img/pokemones/100.png', 'Voltorb', 'Eléctrico', 'Voltorb es un Pokémon de tipo eléctrico introducido en la primera generación. Tiene la forma de una esfera y puede explotar en cualquier momento sin previo aviso.'),
      (101, 'img/pokemones/101.png', 'Electrode', 'Eléctrico', 'Electrode es la evolución de Voltorb. Es más grande y poderoso que su pre-evolución, y puede generar grandes cantidades de electricidad en su interior.'),
      (102, 'img/pokemones/102.png', 'Exeggcute', 'Planta', 'Exeggcute es un Pokémon de tipo planta introducido en la primera generación. Está formado por seis huevos que pueden trabajar juntos para defenderse de los depredadores.'),
      (103, 'img/pokemones/103.png', 'Exeggutor', 'Planta', 'Exeggutor es la evolución de Exeggcute. Es más grande y poderoso que su pre-evolución, y puede lanzar poderosos ataques psíquicos para derrotar a sus enemigos.'),
      (104, 'img/pokemones/104.png', 'Cubone', 'Tierra', 'Cubone es un Pokémon de tipo tierra introducido en la primera generación. Tiene un hueso que utiliza como arma y como protección, y que le recuerda a su madre fallecida.'),
      (105, 'img/pokemones/105.png', 'Marowak', 'Tierra', 'Marowak es la evolución de Cubone. Es más grande y poderoso que su pre-evolución, y puede lanzar potentes ataques con su hueso para defenderse de los depredadores.'),
      (106, 'img/pokemones/106.png', 'Hitmonlee', 'Lucha', 'Hitmonlee es un Pokémon de tipo lucha introducido en la primera generación. Tiene unas piernas extremadamente largas que puede usar para lanzar potentes patadas a sus enemigos.'),
      (107, 'img/pokemones/107.png', 'Hitmonchan', 'Lucha', 'Hitmonchan es un Pokémon de tipo lucha introducido en la primera generación. Tiene unos puños extremadamente rápidos que puede usar para lanzar rápidos golpes a sus enemigos.'),
      (108, 'img/pokemones/108.png', 'Lickitung', 'Normal', 'Lickitung es un Pokémon de tipo normal introducido en la primera generación. Tiene una lengua extremadamente larga que puede usar para atrapar a sus presas y lamerlas.'),
      (109, 'img/pokemones/109.png', 'Koffing', 'Veneno', 'Koffing es un Pokémon de tipo veneno introducido en la primera generación. Tiene un cuerpo lleno de gases tóxicos que puede usar para atacar a sus enemigos y defenderse de los depredadores.'),
      (110, 'img/pokemones/110.png', 'Weezing', 'Veneno', 'Weezing es la evolución de Koffing. Es más grande y poderoso que su pre-evolución, y puede lanzar potentes nubes de gas venenoso para derrotar a sus enemigos.'),
      (111, 'img/pokemones/111.png', 'Rhyhorn', 'Tierra', 'Rhyhorn es un Pokémon de tipo tierra introducido en la primera generación. Tiene un cuerpo extremadamente resistente que puede usar para embestir a sus enemigos y defenderse de los depredadores.'),
      (112, 'img/pokemones/112.png', 'Rhydon', 'Tierra', 'Rhydon es la evolución de Rhyhorn. Es más grande y poderoso que su pre-evolución, y puede lanzar rocas gigantes con su cuerno para aplastar a sus enemigos.'),
      (113, 'img/pokemones/113.png', 'Chansey', 'Normal', 'Chansey es un Pokémon de tipo normal introducido en la primera generación. Tiene un huevo en su bolsa que puede usar para curar a los Pokémon heridos y a las personas enfermas.'),
      (114, 'img/pokemones/114.png', 'Tangela', 'Planta', 'Tangela es un Pokémon de tipo planta introducido en la primera generación. Tiene largas enredaderas que puede usar para atrapar a sus presas y defenderse de los depredadores.'),
      (115, 'img/pokemones/115.png', 'Kangaskhan', 'Normal', 'Kangaskhan es un Pokémon de tipo normal introducido en la primera generación. Es conocido por proteger a sus crías con su vida y por su gran fuerza y resistencia.'),
      (116, 'img/pokemones/116.png', 'Horsea', 'Agua', 'Horsea es un Pokémon de tipo agua introducido en la primera generación. Tiene un cuerpo pequeño y delgado que puede usar para moverse rápidamente en el agua.'),
      (117, 'img/pokemones/117.png', 'Seadra', 'Agua', 'Seadra es la evolución de Horsea. Es más grande y poderoso que su pre-evolución, y puede lanzar potentes chorros de agua para atacar a sus enemigos.'),
      (118, 'img/pokemones/118.png', 'Goldeen', 'Agua', 'Goldeen es un Pokémon de tipo agua introducido en la primera generación. Tiene una aleta en forma de abanico que puede usar para nadar rápidamente en el agua.'),
      (119, 'img/pokemones/119.png', 'Seaking', 'Agua', 'Seaking es la evolución de Goldeen. Es más grande y poderoso que su pre-evolución, y puede lanzar potentes cornadas con su largo cuerno para atacar a sus enemigos.'),
      (120, 'img/pokemones/120.png', 'Staryu', 'Agua', 'Staryu es un Pokémon de tipo agua introducido en la primera generación. Tiene un cuerpo en forma de estrella que puede regenerarse si se le corta un brazo. Puede lanzar potentes chorros de agua para atacar a sus enemigos.'),
      (121, 'img/pokemones/121.png', 'Starmie', 'Agua', 'Starmie es la evolución de Staryu. Es más grande y poderoso que su pre-evolución, y puede lanzar poderosos ataques psíquicos utilizando la energía de su joya central.'),
      (122, 'img/pokemones/122.png', 'Mr. Mime', 'Psíquico', 'Mr. Mime es un Pokémon de tipo psíquico/hada introducido en la primera generación. Es conocido por su habilidad para crear ilusiones y por su amor por el teatro.'),
      (123, 'img/pokemones/123.png', 'Scyther', 'Bicho', 'Scyther es un Pokémon de tipo bicho/volador introducido en la primera generación. Tiene unas afiladas cuchillas en los brazos que puede usar para cortar a sus enemigos en pedazos.'),
      (124, 'img/pokemones/124.png', 'Jynx', 'Hielo', 'Jynx es un Pokémon de tipo hielo introducido en la primera generación. Tiene la capacidad de lanzar ráfagas de aire helado y de hipnotizar a sus enemigos con su baile.'),
      (125, 'img/pokemones/125.png', 'Electabuzz', 'Eléctrico', 'Electabuzz es un Pokémon de tipo eléctrico introducido en la primera generación. Tiene la habilidad de generar grandes cantidades de electricidad y de lanzar potentes ataques eléctricos.'),
      (126, 'img/pokemones/126.png', 'Magmar', 'Fuego', 'Magmar es un Pokémon de tipo fuego introducido en la primera generación. Tiene la capacidad de lanzar bolas de fuego ardiente y de fundir rocas con su aliento.'),
      (127, 'img/pokemones/127.png', 'Pinsir', 'Bicho', 'Pinsir es un Pokémon de tipo bicho introducido en la primera generación. Tiene unas poderosas pinzas que puede usar para atrapar a sus presas y defenderse de los depredadores.'),
      (128, 'img/pokemones/128.png', 'Tauros', 'Normal', 'Tauros es un Pokémon de tipo normal introducido en la primera generación. Es conocido por su gran fuerza y por su temperamento agresivo, y por su habilidad para embestir a sus enemigos con sus cuernos.'),
      (129, 'img/pokemones/129.png', 'Magikarp', 'Agua', 'Magikarp es un Pokémon de tipo agua introducido en la primera generación. Es conocido por ser extremadamente débil y por su capacidad para saltar alto.'),
      (130, 'img/pokemones/130.png', 'Gyarados', 'Agua', 'Gyarados es la evolución de Magikarp. Es más grande y poderoso que su pre-evolución, y puede lanzar potentes ataques de agua para derrotar a sus enemigos.'),
      (131, 'img/pokemones/131.png', 'Lapras', 'Agua', 'Lapras es un Pokémon de tipo agua introducido en la primera generación. Tiene una capa gruesa de grasa que le permite nadar en aguas heladas y llevar a personas en su lomo.'),
      (132, 'img/pokemones/132.png', 'Ditto', 'Normal', 'Ditto es un Pokémon de tipo normal introducido en la primera generación. Tiene la capacidad de transformarse en cualquier otro Pokémon y de copiar sus habilidades y movimientos.'),
      (133, 'img/pokemones/133.png', 'Eevee', 'Normal', 'Eevee es un Pokémon de tipo normal introducido en la primera generación. Es conocido por su capacidad para evolucionar en diferentes tipos de Pokémon dependiendo de las condiciones.'),
      (134, 'img/pokemones/134.png', 'Vaporeon', 'Agua', 'Vaporeon es una de las evoluciones de Eevee. Es un Pokémon de tipo agua extremadamente rápido y ágil que puede nadar a gran velocidad.'),
      (135, 'img/pokemones/135.png', 'Jolteon', 'Eléctrico', 'Jolteon es una de las evoluciones de Eevee. Es un Pokémon de tipo eléctrico extremadamente rápido que puede generar grandes cantidades de electricidad.'),
      (136, 'img/pokemones/136.png', 'Flareon', 'Fuego', 'Flareon es una de las evoluciones de Eevee. Es un Pokémon de tipo fuego extremadamente poderoso que puede lanzar potentes llamas para derrotar a sus enemigos.'),
      (137, 'img/pokemones/137.png', 'Porygon', 'Normal', 'Porygon es un Pokémon de tipo normal introducido en la primera generación. Es conocido por ser creado artificialmente y por su capacidad para moverse libremente dentro de los entornos virtuales.'),
      (138, 'img/pokemones/138.png', 'Omanyte', 'Roca', 'Omanyte es un Pokémon de tipo roca introducido en la primera generación. Tiene una concha dura y resistente que puede usar para protegerse de los ataques enemigos.'),
      (139, 'img/pokemones/139.png', 'Omastar', 'Roca', 'Omastar es la evolución de Omanyte. Es más grande y poderoso que su pre-evolución, y puede lanzar potentes chorros de agua y rocas desde su concha.'),
      (140, 'img/pokemones/140.png', 'Kabuto', 'Roca', 'Kabuto es un Pokémon de tipo roca introducido en la primera generación. Tiene un caparazón duro y resistente que puede usar para defenderse de los ataques enemigos.'),
      (141, 'img/pokemones/141.png', 'Kabutops', 'Roca', 'Kabutops es la evolución de Kabuto. Es más grande y poderoso que su pre-evolución, y puede lanzar potentes ataques con sus afiladas garras y su caparazón resistente.'),
      (142, 'img/pokemones/142.png', 'Aerodactyl', 'Roca', 'Aerodactyl es un Pokémon de tipo roca introducido en la primera generación. Es conocido por ser un feroz depredador que surca los cielos en busca de presas.'),
      (143, 'img/pokemones/143.png', 'Snorlax', 'Normal', 'Snorlax es un Pokémon de tipo normal introducido en la primera generación. Es conocido por su gran tamaño y su apetito voraz, y por su habilidad para dormir en cualquier lugar.'),
      (144, 'img/pokemones/144.png', 'Articuno', 'Hielo', 'Articuno es un Pokémon legendario de tipo hielo/volador introducido en la primera generación. Es conocido por su belleza y su gracia, y por su habilidad para congelar el aire a su alrededor.'),
      (145, 'img/pokemones/145.png', 'Zapdos', 'Eléctrico', 'Zapdos es un Pokémon legendario de tipo eléctrico/volador introducido en la primera generación. Es conocido por su velocidad y agilidad, y por su habilidad para generar potentes tormentas eléctricas.'),
      (146, 'img/pokemones/146.png', 'Moltres', 'Fuego', 'Moltres es un Pokémon legendario de tipo fuego/volador introducido en la primera generación. Es conocido por su majestuosidad y su poderío, y por su habilidad para lanzar llamas ardientes.'),
      (147, 'img/pokemones/147.png', 'Dratini', 'Dragón', 'Dratini es un Pokémon de tipo dragón introducido en la primera generación. Tiene un cuerpo largo y serpenteante que puede usar para moverse rápidamente en el agua y en el aire.'),
      (148, 'img/pokemones/148.png', 'Dragonair', 'Dragón', 'Dragonair es la evolución de Dratini. Es más grande y poderoso que su pre-evolución, y puede lanzar potentes ataques de viento y agua desde sus alas.'),
      (149, 'img/pokemones/149.png', 'Dragonite', 'Dragón', 'Dragonite es la evolución final de Dratini. Es un Pokémon extremadamente poderoso con la capacidad de volar a gran velocidad y de lanzar potentes ataques de fuego y hielo.'),
      (150, 'img/pokemones/150.png', 'Mewtwo', 'Psíquico', 'Mewtwo es un Pokémon legendario de tipo psíquico introducido en la primera generación. Es conocido por su increíble poder psíquico y por su capacidad para controlar la mente de los demás.'),
      (151, 'img/pokemones/151.png', 'Mew', 'Psíquico', 'Mew es un Pokémon legendario de tipo psíquico introducido en la primera generación. Es conocido por su gran variedad de movimientos y por su capacidad para aprender cualquier ataque.');