CREATE DATABASE IF NOT EXISTS pokedex;

USE pokedex;

CREATE TABLE IF NOT EXISTS pokemones (
id INT AUTO_INCREMENT PRIMARY KEY,
numero_identificador INT NOT NULL UNIQUE,
imagen VARCHAR(255) NOT NULL,
nombre VARCHAR(50) NOT NULL,
tipo_1 VARCHAR(100) NOT NULL,
tipo_2 VARCHAR(100),
descripcion TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS administradores (
id INT AUTO_INCREMENT PRIMARY KEY,
user VARCHAR(50) NOT NULL UNIQUE,
pass VARCHAR(30) NOT NULL
);

INSERT INTO `administradores`(`id`, `user`, `pass`) VALUES ('1','pabloR','1357');